services:

  app:
    image: agojin
    build: ./docker/app
    pull_policy: never
    restart: always
    volumes:
      - ./:/app
    links:
      - db
    depends_on:
      - db
    secrets:
      - django_secret_key
      - email_host_password


  db:
    image: dhi.io/postgres:18-alpine3.22
    restart: always
    volumes:
      - ./.db:/var/lib/postgresql
      - ./:/app
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    shm_size: '4gb'
    secrets:
      - postgres_password


secrets:
  django_secret_key:
    file: ./secrets/django_secret_key.txt
  email_host_password:
    file: ./secrets/email_host_password.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
