# Generated by Django 5.2.3 on 2025-06-27 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('data', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'App data',
            },
        ),
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
                ('sort_order', models.IntegerField(default=999)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('coordinates', models.CharField(blank=True, max_length=32, null=True)),
                ('contact_name', models.CharField(max_length=128)),
                ('contact_phone', models.CharField(max_length=128)),
                ('contact_email', models.EmailField(max_length=254)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'facilities',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('chinese_name', models.CharField(max_length=128, null=True, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.TextField(blank=True, default='')),
                ('course_fee', models.IntegerField(blank=True, null=True)),
                ('min_students', models.IntegerField(blank=True, null=True)),
                ('max_students', models.IntegerField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=999)),
                ('image', models.FileField(blank=True, null=True, upload_to='course/')),
                ('course_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='taiping.coursegroup')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='taiping.facility')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField()),
                ('certifications', models.TextField()),
                ('photo', models.FileField(blank=True, null=True, upload_to='instructor/')),
                ('verified', models.BooleanField(db_index=True, default=False)),
                ('calendar_sync', models.BooleanField(db_index=True, default=False)),
                ('date_joined', models.DateField(db_index=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('course_fee', models.IntegerField()),
                ('min_students', models.IntegerField()),
                ('max_students', models.IntegerField()),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=32)),
                ('started', models.BooleanField(db_index=True, default=False)),
                ('auto_start', models.BooleanField(db_index=True, default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taiping.course')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taiping.facility')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taiping.instructor')),
            ],
            options={
                'verbose_name_plural': 'Course classes',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='taiping.instructor'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('alternative_name', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(db_index=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], db_index=True, max_length=8, null=True)),
                ('phone', models.CharField(max_length=128)),
                ('photo', models.FileField(blank=True, null=True, upload_to='student/')),
                ('experience_years', models.IntegerField(blank=True, default=0)),
                ('styles_trained', models.TextField(blank=True, null=True)),
                ('medical_conditions', models.TextField(blank=True, null=True)),
                ('preferred_languages', models.TextField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=128, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=128, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('started', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taiping.courseclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taiping.student')),
            ],
        ),
        migrations.CreateModel(
            name='Compliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('compliance_type', models.CharField(choices=[('instructor terms and conditions', 'Instructor Terms And Conditions'), ('terms and conditions', 'Terms And Conditions'), ('indemnity waiver', 'Indemnity Waiver')], db_index=True, max_length=32)),
                ('data', models.TextField()),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='taiping.instructor')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='taiping.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taiping.course')),
                ('dependent_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='taiping.course')),
            ],
            options={
                'verbose_name_plural': 'Course dependencies',
                'constraints': [models.UniqueConstraint(fields=('course', 'dependent_course'), name='course_dependency__unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='courseclass',
            constraint=models.UniqueConstraint(fields=('course', 'start_date', 'instructor'), name='course_class__unique'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('course_class', 'student'), name='registration__unique'),
        ),
    ]
