# Generated by Django 4.2.14 on 2024-07-20 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
                ('course_fee', models.IntegerField()),
                ('min_students', models.IntegerField()),
                ('max_students', models.IntegerField()),
                ('next_class', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('notes', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taiping.course')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('tel', models.CharField(max_length=32)),
                ('comments', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taiping.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('non_registration_id', models.IntegerField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taiping.courseclass')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='taiping.registration')),
            ],
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('course_class', 'registration', 'non_registration_id'), name='student__unique'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('course', 'email'), name='registration__unique'),
        ),
        migrations.AddConstraint(
            model_name='courseclass',
            constraint=models.UniqueConstraint(fields=('course', 'name'), name='course_class__unique'),
        ),
    ]
