# Generated by Django 5.2.3 on 2025-06-27 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('class_date', models.DateField(db_index=True)),
                ('class_time_start', models.TimeField(db_index=True)),
                ('class_time_end', models.TimeField(db_index=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taiping.courseclass')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('course_class', 'class_date', 'class_time_start', 'class_time_end'), name='course_class_schedule__unique')],
            },
        ),
    ]
