# Generated by Django 5.2.7 on 2025-11-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='small_image',
            field=models.FileField(blank=True, null=True, upload_to='course/'),
        ),
    ]
