# Generated by Django 5.2.8 on 2026-01-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0002_course_small_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='small_image',
            field=models.FileField(blank=True, null=True, upload_to='course/small/'),
        ),
    ]
