# Generated by Django 5.2.10 on 2026-01-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0003_alter_course_small_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='facility',
            name='google_map_embed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
