# Generated by Django 6.0.2 on 2026-02-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0004_remove_facility_coordinates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='class_type',
            field=models.CharField(db_index=True, default='Seminar', max_length=128),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='class_duration',
            field=models.CharField(db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='class_type',
            field=models.CharField(db_index=True, default='Seminar', max_length=128),
        ),
        migrations.AddField(
            model_name='facility',
            name='country',
            field=models.TextField(db_index=True, default='Singapore'),
        ),
    ]
