# Generated by Django 6.0.2 on 2026-02-08 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0005_course_class_type_courseclass_class_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='class_type',
        ),
    ]
