# Generated by Django 5.0.7 on 2024-07-30 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0005_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
