# Generated by Django 5.0.7 on 2024-08-02 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0006_alter_config_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taiping.course')),
                ('dependent_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='taiping.course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
