# Generated by Django 6.0.3 on 2026-03-05 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0006_remove_course_class_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseClassStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('dropped_out', 'Dropped Out')], db_index=True, default='enrolled', max_length=16)),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taiping.courseclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taiping.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('course_class', 'student'), name='taiping_courseclassstudent__unique')],
            },
        ),
    ]
