# Generated by Django 5.2.3 on 2025-06-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0006_student'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='courseclass',
            name='course_class__unique',
        ),
        migrations.AddConstraint(
            model_name='courseclass',
            constraint=models.UniqueConstraint(fields=('course', 'start_date', 'instructor'), name='course_class__unique'),
        ),
    ]
