# Generated by Django 5.2.3 on 2025-06-11 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0007_remove_courseclass_course_class__unique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseclass',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'user_type': 'instructor'}, on_delete=django.db.models.deletion.PROTECT, to='taiping.instructor'),
        ),
    ]
