# Generated by Django 5.0.7 on 2024-08-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0007_coursedependency'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='static_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
