# Generated by Django 6.0.3 on 2026-03-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0007_courseclassstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='alternative_name',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
