# Generated by Django 5.0.7 on 2024-08-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0008_course_static_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='sort_order',
            field=models.IntegerField(blank=True, default=999, null=True),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
    ]
