# Generated by Django 5.2.3 on 2025-06-11 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0008_alter_courseclass_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseclass',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taiping.instructor'),
        ),
    ]
