# Generated by Django 6.0.3 on 2026-03-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0008_instructor_alternative_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='position',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
