# Generated by Django 6.0.3 on 2026-03-06 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0009_instructor_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseClassStudentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('course_class_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taiping.courseclassschedule')),
                ('course_class_student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taiping.courseclassstudent')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('course_class_student', 'course_class_schedule'), name='taiping_courseclassstudentsession__unique')],
            },
        ),
    ]
