# Generated by Django 5.2.3 on 2025-06-11 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0009_alter_courseclass_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseclass',
            name='name',
        ),
    ]
