# Generated by Django 5.0.7 on 2024-08-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0009_alter_course_sort_order_alter_courseclass_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
