# Generated by Django 6.0.3 on 2026-03-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0010_courseclassstudentsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseclassstudent',
            name='status',
            field=models.CharField(choices=[('enrolled', 'Enrolled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('dropped_out', 'Dropped Out'), ('cancelled', 'Cancelled')], db_index=True, default='enrolled', max_length=16),
        ),
    ]
