# Generated by Django 5.2.3 on 2025-06-11 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0011_alter_facility_address_alter_facility_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'facilities'},
        ),
        migrations.AddField(
            model_name='course',
            name='default_course_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='default_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='taiping.facility'),
        ),
        migrations.AddField(
            model_name='course',
            name='default_instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='taiping.instructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='default_max_students',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='default_min_students',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
