# Generated by Django 6.0.3 on 2026-03-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0011_alter_courseclassstudent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=32),
        ),
    ]
