# Generated by Django 5.2.3 on 2025-06-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0012_alter_facility_options_course_default_course_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='chinese_name',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
