# Generated by Django 5.2.3 on 2025-06-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0013_course_chinese_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.TextField(default=''),
        ),
    ]
