# Generated by Django 5.2.3 on 2025-06-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0016_rename_coordinated_facility_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseclass',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=32),
        ),
    ]
