# Generated by Django 5.2.3 on 2025-06-13 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0017_alter_courseclass_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taiping.course')),
                ('dependent_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='taiping.course')),
            ],
            options={
                'verbose_name_plural': 'Course dependencies',
                'constraints': [models.UniqueConstraint(fields=('course', 'dependent_course'), name='course_dependency__unique')],
            },
        ),
    ]
