# Generated by Django 5.2.3 on 2025-06-13 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0018_coursedependency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registration',
            name='registration__unique',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='course',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='tel',
        ),
        migrations.AddField(
            model_name='registration',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='course_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='taiping.courseclass'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('course_class', 'student'), name='registration__unique'),
        ),
    ]
