# Generated by Django 5.2.3 on 2025-06-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0019_remove_registration_registration__unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclass',
            name='started',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='auto_start',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='started',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
