# Generated by Django 5.2.3 on 2025-06-20 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0026_delete_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('started', models.BooleanField(db_index=True, default=False)),
                ('completed', models.BooleanField(db_index=True, default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taiping.courseclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taiping.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('course_class', 'student'), name='registration__unique')],
            },
        ),
    ]
