# Generated by Django 5.2.3 on 2025-06-20 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0027_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='profile_photo',
            new_name='photo',
        ),
    ]
