# Generated by Django 5.2.3 on 2025-06-25 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0033_compliance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliance',
            name='user',
        ),
        migrations.AddField(
            model_name='compliance',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='taiping.student'),
            preserve_default=False,
        ),
    ]
