# Generated by Django 5.2.3 on 2025-06-25 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0034_remove_compliance_user_compliance_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliance',
            name='name',
        ),
    ]
