# Generated by Django 5.2.3 on 2025-06-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0035_remove_compliance_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliance',
            name='compliance_type',
            field=models.CharField(choices=[('instructor terms and conditions', 'Instructor Terms And Conditions'), ('terms and conditions', 'Terms And Conditions'), ('indemnity waiver', 'Indemnity Waiver')], db_index=True, max_length=32),
        ),
    ]
