# Generated by Django 5.0.7 on 2024-07-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0002_coursegroup_alter_courseclass_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sort_order',
            field=models.IntegerField(default=999),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='sort_order',
            field=models.IntegerField(default=999),
        ),
    ]
