# Generated by Django 5.2.3 on 2025-06-11 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0004_course_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('coordinated', models.CharField(blank=True, max_length=32, null=True)),
                ('contact_name', models.CharField(max_length=128)),
                ('contact_phone', models.CharField(max_length=128)),
                ('contact_email', models.EmailField(max_length=254)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_fee',
        ),
        migrations.RemoveField(
            model_name='course',
            name='max_students',
        ),
        migrations.RemoveField(
            model_name='course',
            name='min_students',
        ),
        migrations.RemoveField(
            model_name='course',
            name='next_class',
        ),
        migrations.AddField(
            model_name='courseclass',
            name='auto_start',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='course_fee',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseclass',
            name='max_students',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseclass',
            name='min_students',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseclass',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], db_index=True, default='DRAFT', max_length=32),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='taiping.coursegroup'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='facility',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='taiping.facility'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField()),
                ('certifications', models.TextField()),
                ('photo', models.FileField(upload_to='')),
                ('verified', models.BooleanField(db_index=True, default=False)),
                ('calendar_sync', models.BooleanField(db_index=True, default=False)),
                ('date_joined', models.DateField(db_index=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='courseclass',
            name='instructor',
            field=models.ForeignKey(default=0, limit_choices_to={'user|_type': 'instructor'}, on_delete=django.db.models.deletion.PROTECT, to='taiping.instructor'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
