# Generated by Django 5.2.3 on 2025-06-12 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0014_course_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='default_course_fee',
            new_name='course_fee',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='default_facility',
            new_name='facility',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='default_instructor',
            new_name='instructor',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='default_max_students',
            new_name='max_students',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='default_min_students',
            new_name='min_students',
        ),
    ]
