# Generated by Django 5.2.3 on 2025-06-12 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0015_rename_default_course_fee_course_course_fee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='coordinated',
            new_name='coordinates',
        ),
    ]
