# Generated by Django 5.2.3 on 2025-06-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0021_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='photo',
            field=models.FileField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_photo',
            field=models.FileField(upload_to='img/'),
        ),
    ]
