# Generated by Django 5.2.3 on 2025-06-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0022_alter_course_image_alter_instructor_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='img/'),
        ),
    ]
