# Generated by Django 5.2.3 on 2025-06-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0023_alter_instructor_photo_alter_student_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='course/'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='instructor/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='student/'),
        ),
    ]
