# Generated by Django 5.2.3 on 2025-06-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0024_alter_course_image_alter_instructor_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
