# Generated by Django 5.2.3 on 2025-06-20 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0025_alter_course_short_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
