# Generated by Django 5.2.3 on 2025-06-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0028_rename_profile_photo_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
