# Generated by Django 5.2.3 on 2025-06-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0031_alter_appdata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appdata',
            options={'verbose_name_plural': 'App data'},
        ),
    ]
