# Generated by Django 5.2.3 on 2025-06-27 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiping', '0036_alter_compliance_compliance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliance',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='taiping.instructor'),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='taiping.student'),
        ),
    ]
